apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod-label-az-b-example
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo 'Event: Label Pod is Running...'; sleep 10; done"]
  nodeSelector:
    label: "true"
    topology.kubernetes.io/zone: "kr-central-2-b"
