apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod-toleration-example
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo 'Event: Tolerations Pod is Running...'; sleep 10; done"]
  nodeSelector:
    taint: "true"
  tolerations:
  - key: "tutorial"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
