apiVersion: v1
kind: Pod
metadata:
  name: s3-access-pod
spec:
  containers:
  - name: s3-container
    image: ubuntu
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: s3-secret
          key: credential
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: s3-secret
          key: credential-secret
    - name: AWS_REGION
      valueFrom:
        secretKeyRef:
          name: s3-secret
          key: region
    - name: AWS_ENDPOINT_URL
      valueFrom:
        secretKeyRef:
          name: s3-secret
          key: endpoint-url
    command: ["/bin/sh", "-c"]
    args:
    - |
      apt update && \
      apt install -y curl unzip && \
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
      unzip awscliv2.zip && \
      ./aws/install && \
      aws --version && \
      sleep 3600
